"""Service layer — the single entry point for every research operation.

Callers (HTTP routes, scripts, notebooks) construct a parameter object and a
:class:`RunContext`, then call one function. No caller implements domain logic.

Exports are resolved lazily. Eagerly importing every submodule here would make
``quant_trade.data.sync`` (which needs :class:`RunContext` for its optional
progress reporting) import the whole domain layer back, and would also drag
pandas and LightGBM into callers that only want a context object.
"""

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from quant_trade.services.backtest import (
        BacktestParams,
        BacktestResult,
        run_backtest_service,
    )
    from quant_trade.services.backtest_query import (
        BacktestComparisonEntry,
        BacktestComparisonParams,
        BacktestComparisonResult,
        BacktestDetailParams,
        BacktestDetailResult,
        BacktestPositionRow,
        BacktestRunListParams,
        BacktestRunListResult,
        BacktestRunSummary,
        BacktestSeries,
        BacktestTradeParams,
        BacktestTradeResult,
        BacktestTradeRow,
        backtest_comparison,
        backtest_detail,
        backtest_run_list,
        backtest_trades,
    )
    from quant_trade.services.context import (
        NULL_CONTEXT,
        CancelToken,
        LogSink,
        ProgressSink,
        RunContext,
    )
    from quant_trade.services.data import (
        DataStatus,
        DataStatusParams,
        DataSyncParams,
        DataSyncResult,
        data_status,
        sync_market_data,
    )
    from quant_trade.services.factor_analysis import (
        FactorCorrelationParams,
        FactorCorrelationResult,
        FactorCoverageEntry,
        FactorCoverageParams,
        FactorCoverageResult,
        FactorICComputeParams,
        FactorICComputeResult,
        FactorICDecayEntry,
        FactorICDecayResult,
        FactorICOverviewParams,
        FactorICOverviewRow,
        FactorICPoint,
        FactorICQueryParams,
        FactorICSeriesResult,
        FactorQuantileParams,
        FactorQuantileResult,
        compute_factor_ic,
        factor_correlation,
        factor_coverage,
        factor_ic_decay,
        factor_ic_overview,
        factor_ic_series,
        factor_quantile_backtest,
    )
    from quant_trade.services.factors import (
        Alpha158Params,
        FactorComputeParams,
        FactorICParams,
        FactorListParams,
        compute_alpha158,
        compute_factors,
        factor_ic_summary,
        list_factors,
    )
    from quant_trade.services.model_query import (
        ModelEvaluationParams,
        ModelEvaluationResult,
        ModelICPoint,
        ModelImportanceEntry,
        ModelRunListParams,
        ModelRunListResult,
        ModelRunSummary,
        ModelYearSummary,
        model_evaluation,
        model_run_list,
    )
    from quant_trade.services.models import (
        LightGBMParams,
        PredictParams,
        PredictResult,
        TrainParams,
        TrainResult,
        predict_for_date,
        train_model,
    )
    from quant_trade.services.params import ServiceParams
    from quant_trade.services.queries import (
        CalendarDay,
        FactorNamesParams,
        TradeCalendarParams,
        TradeCalendarView,
        UniverseCoverage,
        UniverseCoverageParams,
        list_factor_names,
        trade_calendar,
        universe_coverage,
    )
    from quant_trade.services.report import WeeklyReportParams, WeeklyReportResult, generate_weekly
    from quant_trade.services.report_query import (
        ReportContent,
        ReportDetail,
        ReportDetailParams,
        ReportListParams,
        ReportListResult,
        ReportSummary,
        report_detail,
        report_html,
        report_list,
    )
    from quant_trade.services.strategies import (
        SignalParams,
        SignalSummary,
        StrategyListParams,
        generate_strategy_signals,
        list_strategies,
        run_strategy_signals,
    )
    from quant_trade.services.strategy_query import (
        StrategyRunListParams,
        StrategyRunListResult,
        StrategyRunSummary,
        StrategySignalQueryParams,
        StrategySignalResult,
        StrategySignalRow,
        strategy_run_list,
        strategy_signals,
    )

__all__ = [
    "NULL_CONTEXT",
    "Alpha158Params",
    "BacktestComparisonEntry",
    "BacktestComparisonParams",
    "BacktestComparisonResult",
    "BacktestDetailParams",
    "BacktestDetailResult",
    "BacktestParams",
    "BacktestPositionRow",
    "BacktestResult",
    "BacktestRunListParams",
    "BacktestRunListResult",
    "BacktestRunSummary",
    "BacktestSeries",
    "BacktestTradeParams",
    "BacktestTradeResult",
    "BacktestTradeRow",
    "CalendarDay",
    "CancelToken",
    "DataStatus",
    "DataStatusParams",
    "DataSyncParams",
    "DataSyncResult",
    "FactorComputeParams",
    "FactorCorrelationParams",
    "FactorCorrelationResult",
    "FactorCoverageEntry",
    "FactorCoverageParams",
    "FactorCoverageResult",
    "FactorICComputeParams",
    "FactorICComputeResult",
    "FactorICDecayEntry",
    "FactorICDecayResult",
    "FactorICOverviewParams",
    "FactorICOverviewRow",
    "FactorICParams",
    "FactorICPoint",
    "FactorICQueryParams",
    "FactorICSeriesResult",
    "FactorListParams",
    "FactorNamesParams",
    "FactorQuantileParams",
    "FactorQuantileResult",
    "LightGBMParams",
    "LogSink",
    "PredictParams",
    "PredictResult",
    "ModelEvaluationParams",
    "ModelEvaluationResult",
    "ModelICPoint",
    "ModelImportanceEntry",
    "ModelRunListParams",
    "ModelRunListResult",
    "ModelRunSummary",
    "ModelYearSummary",
    "ProgressSink",
    "ReportContent",
    "ReportDetail",
    "ReportDetailParams",
    "ReportListParams",
    "ReportListResult",
    "ReportSummary",
    "RunContext",
    "ServiceParams",
    "SignalParams",
    "SignalSummary",
    "StrategyListParams",
    "StrategyRunListParams",
    "StrategyRunListResult",
    "StrategyRunSummary",
    "StrategySignalQueryParams",
    "StrategySignalResult",
    "StrategySignalRow",
    "TradeCalendarParams",
    "TradeCalendarView",
    "TrainParams",
    "TrainResult",
    "UniverseCoverage",
    "UniverseCoverageParams",
    "WeeklyReportParams",
    "WeeklyReportResult",
    "backtest_comparison",
    "backtest_detail",
    "backtest_run_list",
    "backtest_trades",
    "compute_alpha158",
    "compute_factors",
    "compute_factor_ic",
    "data_status",
    "factor_correlation",
    "factor_coverage",
    "factor_ic_decay",
    "factor_ic_overview",
    "factor_ic_series",
    "factor_ic_summary",
    "factor_quantile_backtest",
    "generate_strategy_signals",
    "generate_weekly",
    "list_factor_names",
    "list_factors",
    "list_strategies",
    "model_evaluation",
    "model_run_list",
    "predict_for_date",
    "report_detail",
    "report_html",
    "report_list",
    "run_backtest_service",
    "run_strategy_signals",
    "strategy_run_list",
    "strategy_signals",
    "sync_market_data",
    "trade_calendar",
    "train_model",
    "universe_coverage",
]

_MODULE_BY_NAME: dict[str, str] = {
    "NULL_CONTEXT": "quant_trade.services.context",
    "CancelToken": "quant_trade.services.context",
    "LogSink": "quant_trade.services.context",
    "ProgressSink": "quant_trade.services.context",
    "RunContext": "quant_trade.services.context",
    "ServiceParams": "quant_trade.services.params",
    "DataStatus": "quant_trade.services.data",
    "DataStatusParams": "quant_trade.services.data",
    "DataSyncParams": "quant_trade.services.data",
    "DataSyncResult": "quant_trade.services.data",
    "data_status": "quant_trade.services.data",
    "sync_market_data": "quant_trade.services.data",
    "Alpha158Params": "quant_trade.services.factors",
    "FactorComputeParams": "quant_trade.services.factors",
    "FactorICComputeParams": "quant_trade.services.factor_analysis",
    "FactorICComputeResult": "quant_trade.services.factor_analysis",
    "FactorICDecayEntry": "quant_trade.services.factor_analysis",
    "FactorICDecayResult": "quant_trade.services.factor_analysis",
    "FactorICOverviewParams": "quant_trade.services.factor_analysis",
    "FactorICOverviewRow": "quant_trade.services.factor_analysis",
    "FactorICPoint": "quant_trade.services.factor_analysis",
    "FactorICQueryParams": "quant_trade.services.factor_analysis",
    "FactorICSeriesResult": "quant_trade.services.factor_analysis",
    "FactorCoverageEntry": "quant_trade.services.factor_analysis",
    "FactorCoverageParams": "quant_trade.services.factor_analysis",
    "FactorCoverageResult": "quant_trade.services.factor_analysis",
    "FactorCorrelationParams": "quant_trade.services.factor_analysis",
    "FactorCorrelationResult": "quant_trade.services.factor_analysis",
    "FactorQuantileParams": "quant_trade.services.factor_analysis",
    "FactorQuantileResult": "quant_trade.services.factor_analysis",
    "compute_factor_ic": "quant_trade.services.factor_analysis",
    "factor_correlation": "quant_trade.services.factor_analysis",
    "factor_coverage": "quant_trade.services.factor_analysis",
    "factor_ic_decay": "quant_trade.services.factor_analysis",
    "factor_ic_overview": "quant_trade.services.factor_analysis",
    "factor_ic_series": "quant_trade.services.factor_analysis",
    "factor_quantile_backtest": "quant_trade.services.factor_analysis",
    "FactorICParams": "quant_trade.services.factors",
    "FactorListParams": "quant_trade.services.factors",
    "compute_alpha158": "quant_trade.services.factors",
    "compute_factors": "quant_trade.services.factors",
    "factor_ic_summary": "quant_trade.services.factors",
    "list_factors": "quant_trade.services.factors",
    "SignalParams": "quant_trade.services.strategies",
    "SignalSummary": "quant_trade.services.strategies",
    "StrategyListParams": "quant_trade.services.strategies",
    "generate_strategy_signals": "quant_trade.services.strategies",
    "list_strategies": "quant_trade.services.strategies",
    "run_strategy_signals": "quant_trade.services.strategies",
    "StrategyRunListParams": "quant_trade.services.strategy_query",
    "StrategyRunListResult": "quant_trade.services.strategy_query",
    "StrategyRunSummary": "quant_trade.services.strategy_query",
    "StrategySignalQueryParams": "quant_trade.services.strategy_query",
    "StrategySignalResult": "quant_trade.services.strategy_query",
    "StrategySignalRow": "quant_trade.services.strategy_query",
    "strategy_run_list": "quant_trade.services.strategy_query",
    "strategy_signals": "quant_trade.services.strategy_query",
    "LightGBMParams": "quant_trade.services.models",
    "ModelEvaluationParams": "quant_trade.services.model_query",
    "ModelEvaluationResult": "quant_trade.services.model_query",
    "ModelICPoint": "quant_trade.services.model_query",
    "ModelImportanceEntry": "quant_trade.services.model_query",
    "ModelRunListParams": "quant_trade.services.model_query",
    "ModelRunListResult": "quant_trade.services.model_query",
    "ModelRunSummary": "quant_trade.services.model_query",
    "ModelYearSummary": "quant_trade.services.model_query",
    "model_evaluation": "quant_trade.services.model_query",
    "model_run_list": "quant_trade.services.model_query",
    "PredictParams": "quant_trade.services.models",
    "PredictResult": "quant_trade.services.models",
    "TrainParams": "quant_trade.services.models",
    "TrainResult": "quant_trade.services.models",
    "predict_for_date": "quant_trade.services.models",
    "train_model": "quant_trade.services.models",
    "BacktestParams": "quant_trade.services.backtest",
    "BacktestResult": "quant_trade.services.backtest",
    "run_backtest_service": "quant_trade.services.backtest",
    "BacktestComparisonEntry": "quant_trade.services.backtest_query",
    "BacktestComparisonParams": "quant_trade.services.backtest_query",
    "BacktestComparisonResult": "quant_trade.services.backtest_query",
    "BacktestDetailParams": "quant_trade.services.backtest_query",
    "BacktestDetailResult": "quant_trade.services.backtest_query",
    "BacktestPositionRow": "quant_trade.services.backtest_query",
    "BacktestRunListParams": "quant_trade.services.backtest_query",
    "BacktestRunListResult": "quant_trade.services.backtest_query",
    "BacktestRunSummary": "quant_trade.services.backtest_query",
    "BacktestSeries": "quant_trade.services.backtest_query",
    "BacktestTradeParams": "quant_trade.services.backtest_query",
    "BacktestTradeResult": "quant_trade.services.backtest_query",
    "BacktestTradeRow": "quant_trade.services.backtest_query",
    "backtest_comparison": "quant_trade.services.backtest_query",
    "backtest_detail": "quant_trade.services.backtest_query",
    "backtest_run_list": "quant_trade.services.backtest_query",
    "backtest_trades": "quant_trade.services.backtest_query",
    "WeeklyReportParams": "quant_trade.services.report",
    "WeeklyReportResult": "quant_trade.services.report",
    "generate_weekly": "quant_trade.services.report",
    "ReportContent": "quant_trade.services.report_query",
    "ReportDetail": "quant_trade.services.report_query",
    "ReportDetailParams": "quant_trade.services.report_query",
    "ReportListParams": "quant_trade.services.report_query",
    "ReportListResult": "quant_trade.services.report_query",
    "ReportSummary": "quant_trade.services.report_query",
    "report_detail": "quant_trade.services.report_query",
    "report_html": "quant_trade.services.report_query",
    "report_list": "quant_trade.services.report_query",
    "CalendarDay": "quant_trade.services.queries",
    "FactorNamesParams": "quant_trade.services.queries",
    "TradeCalendarParams": "quant_trade.services.queries",
    "TradeCalendarView": "quant_trade.services.queries",
    "UniverseCoverage": "quant_trade.services.queries",
    "UniverseCoverageParams": "quant_trade.services.queries",
    "list_factor_names": "quant_trade.services.queries",
    "trade_calendar": "quant_trade.services.queries",
    "universe_coverage": "quant_trade.services.queries",
}


def __getattr__(name: str) -> Any:
    """Resolve a public service name to its defining module on first access."""
    module_path = _MODULE_BY_NAME.get(name)
    if module_path is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    import importlib

    return getattr(importlib.import_module(module_path), name)
